### ISSUE TITLE
Component  - Landing Page

### ISSUE THREAD

**Issue by tiffzhong** [tiffzhong/taskrabbit#1]
All 3 of us have 3 sections on the landing page

-Header (Tiff)
-Location Finder (Ice boxed)
-Task Cards (JT)
-How it works (Natalie)

Font: "Proxima", Arial, Helvetica, san-serif

---

9 Tasks:
1. Mounting & Installation
2. Moving & Packing
3. Furniture Assembly
4. Home Improvement (Fixing)
5. Yard Work/Landscaping/Garden
6. Delivery Service
7. Cleaning Service
8. Pet Service
9. Cooking Service

(Ice Box Ideas)
-Entertainer
-Car Mechanic
-Hooker

**Comment by npulver00** [comment]
hello
